name: Build And Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build
      env:
          TESTS_CMAKE: cmake
          TESTS_CMAKE_COMPILER: gcc
          TESTS_CMAKE_GENERATOR: "Unix Makefiles"
          TESTS_EXE_EXTENSION: none
      run: bash build.sh buildAll --clear --release

    - name: Test
      env:
          TESTS_CMAKE: cmake
          TESTS_CMAKE_COMPILER: gcc
          TESTS_CMAKE_GENERATOR: "Unix Makefiles"
          TESTS_EXE_EXTENSION: none
      run: bash build.sh testAll --clear --release
