name: Build And Test

on:
  push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]

    env:
      TESTS_CMAKE: cmake
      TESTS_CMAKE_COMPILER: gcc
      TESTS_CMAKE_GENERATOR: "Unix Makefiles"
      TESTS_EXE_EXTENSION: none

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build
      run: bash build.sh buildAll --clear --release

    - name: Test
      run: bash build.sh testAll --clear --release
